"""empty message

Revision ID: 001318d7b056
Revises: 7e6c972ff746
Create Date: 2023-05-17 20:38:58.076457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001318d7b056'
down_revision = '7e6c972ff746'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ncmr', sa.Column('revision', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ncmr', 'revision')
    # ### end Alembic commands ###
