"""empty message

Revision ID: 07004720c8a1
Revises: f770130d3180
Create Date: 2023-05-24 17:51:22.538107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07004720c8a1'
down_revision = 'f770130d3180'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dvtn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_utc', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('_status', sa.Integer(), nullable=True),
    sa.Column('phase_0_due_utc', sa.BigInteger(), nullable=True),
    sa.Column('dvtn_description', sa.String(), nullable=True),
    sa.Column('dvtn_description_raw', sa.String(), nullable=True),
    sa.Column('is_unplanned', sa.Integer(), nullable=True),
    sa.Column('initial_corrections', sa.String(), nullable=True),
    sa.Column('initial_corrections_raw', sa.String(), nullable=True),
    sa.Column('phase_1_due_utc', sa.BigInteger(), nullable=True),
    sa.Column('outstanding_corrections', sa.String(), nullable=True),
    sa.Column('outstanding_corrections_raw', sa.String(), nullable=True),
    sa.Column('corrections_assignee_id', sa.Integer(), nullable=True),
    sa.Column('phase_2_due_utc', sa.BigInteger(), nullable=True),
    sa.Column('final_corrections', sa.String(), nullable=True),
    sa.Column('final_corrections_raw', sa.String(), nullable=True),
    sa.Column('phase_3_due_utc', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['corrections_assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number', 'organization_id', name='dvtn_org_number_unique')
    )
    op.create_index(op.f('ix_dvtn_number'), 'dvtn', ['number'], unique=False)
    op.create_table('dvtn_approval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['dvtn.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dvtn_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.Integer(), nullable=True),
    sa.Column('created_ip', sa.String(length=64), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['dvtn.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dvtn_audit')
    op.drop_table('dvtn_approval')
    op.drop_index(op.f('ix_dvtn_number'), table_name='dvtn')
    op.drop_table('dvtn')
    # ### end Alembic commands ###
