"""empty message

Revision ID: 0e2ab5ebd716
Revises: d82f4e11c063
Create Date: 2023-05-25 21:22:49.745415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e2ab5ebd716'
down_revision = 'd82f4e11c063'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('dvtn_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'files', 'dvtn', ['dvtn_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_column('files', 'dvtn_id')
    # ### end Alembic commands ###
