"""empty message

Revision ID: 11331d4310b2
Revises: a710212c372b
Create Date: 2023-06-18 23:49:52.410114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11331d4310b2'
down_revision = 'a710212c372b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('item_view_user_unique', 'item_view', ['item_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('item_view_user_unique', 'item_view', type_='unique')
    # ### end Alembic commands ###
