"""empty message

Revision ID: 1298331da4eb
Revises: f226907fbfac
Create Date: 2023-04-30 09:33:45.917178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1298331da4eb'
down_revision = 'f226907fbfac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_log', sa.Column('creation_ip', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_log', 'creation_ip')
    # ### end Alembic commands ###
