"""empty message

Revision ID: 13a89f0a6368
Revises: 4777f1d3eb42
Create Date: 2023-06-10 15:49:00.131011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13a89f0a6368'
down_revision = '4777f1d3eb42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chng_assessor_relationship')
    op.add_column('chng_approver_relationship', sa.Column('group_id', sa.Integer(), nullable=True))
    op.drop_constraint('chng_user_approver_rel_unique', 'chng_approver_relationship', type_='unique')
    op.create_unique_constraint('chng_user_approver_rel_unique', 'chng_approver_relationship', ['record_id', 'group_id'])
    op.drop_constraint('chng_approver_relationship_user_id_fkey', 'chng_approver_relationship', type_='foreignkey')
    op.create_foreign_key(None, 'chng_approver_relationship', 'chng_approver_group', ['group_id'], ['id'])
    op.drop_column('chng_approver_relationship', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chng_approver_relationship', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chng_approver_relationship', type_='foreignkey')
    op.create_foreign_key('chng_approver_relationship_user_id_fkey', 'chng_approver_relationship', 'users', ['user_id'], ['id'])
    op.drop_constraint('chng_user_approver_rel_unique', 'chng_approver_relationship', type_='unique')
    op.create_unique_constraint('chng_user_approver_rel_unique', 'chng_approver_relationship', ['record_id', 'user_id'])
    op.drop_column('chng_approver_relationship', 'group_id')
    op.create_table('chng_assessor_relationship',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('record_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['chng.id'], name='chng_assessor_relationship_record_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='chng_assessor_relationship_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chng_assessor_relationship_pkey'),
    sa.UniqueConstraint('record_id', 'user_id', name='chng_user_assessor_rel_unique')
    )
    # ### end Alembic commands ###
