"""empty message

Revision ID: 13fd57d7ea65
Revises: a3fbe3a15cc4
Create Date: 2023-05-04 21:27:30.333700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13fd57d7ea65'
down_revision = 'a3fbe3a15cc4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_otp_code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_otp_code')
    # ### end Alembic commands ###
