"""empty message

Revision ID: 141df2e9a22e
Revises: 263f8ef77451
Create Date: 2023-05-15 20:33:41.192613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '141df2e9a22e'
down_revision = '263f8ef77451'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
