"""empty message

Revision ID: 16bc99828492
Revises: 520a2d5d4e93
Create Date: 2023-05-21 20:32:57.394688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16bc99828492'
down_revision = '520a2d5d4e93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_doc_control', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_mrb', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_quality_management', sa.Boolean(), nullable=True))
    op.drop_column('users', 'special_role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('special_role', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_quality_management')
    op.drop_column('users', 'is_mrb')
    op.drop_column('users', 'is_doc_control')
    # ### end Alembic commands ###
