"""empty message

Revision ID: 18094fc90c08
Revises: f08924ffcd80
Create Date: 2023-04-30 15:50:35.455594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18094fc90c08'
down_revision = 'f08924ffcd80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('license_assigned_utc', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'license_assigned_utc')
    # ### end Alembic commands ###
