"""empty message

Revision ID: 1b5228be1198
Revises: 254ed84e745a
Create Date: 2023-05-23 21:36:22.777991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b5228be1198'
down_revision = '254ed84e745a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('sha512', sa.String(length=128), nullable=True))
    op.add_column('files', sa.Column('file_name', sa.String(), nullable=True))
    op.drop_column('files', 'sha_256')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('sha_256', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.drop_column('files', 'file_name')
    op.drop_column('files', 'sha512')
    # ### end Alembic commands ###
