"""empty message

Revision ID: 1ec6b80934dd
Revises: 13a89f0a6368
Create Date: 2023-06-10 16:07:11.820643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ec6b80934dd'
down_revision = '13a89f0a6368'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chng_approver_relationship', 'record_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chng_approver_relationship', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chng_approver_relationship', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chng_approver_relationship', 'record_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
