"""empty message

Revision ID: 2199a70c0eec
Revises: b793e2d1dec6
Create Date: 2023-06-01 21:23:50.156832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2199a70c0eec'
down_revision = 'b793e2d1dec6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('item_org_custom_number_unique', 'item', ['custom_number', 'organization_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('item_org_custom_number_unique', 'item', type_='unique')
    # ### end Alembic commands ###
