"""empty message

Revision ID: 258519d1fe46
Revises: 1ec6b80934dd
Create Date: 2023-06-10 16:10:41.620094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258519d1fe46'
down_revision = '1ec6b80934dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chnge_approver_group_relationship', 'record_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chnge_approver_group_relationship', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('approver_group_rel_grp_user_unique', 'chnge_approver_group_relationship', ['record_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('approver_group_rel_grp_user_unique', 'chnge_approver_group_relationship', type_='unique')
    op.alter_column('chnge_approver_group_relationship', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chnge_approver_group_relationship', 'record_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
