"""empty message

Revision ID: 263f8ef77451
Revises: b329656be69a
Create Date: 2023-05-14 18:20:53.915047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '263f8ef77451'
down_revision = 'b329656be69a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ncmr', sa.Column('new_comments', sa.String(), nullable=True))
    op.add_column('ncmr', sa.Column('new_comments_raw', sa.String(), nullable=True))
    op.add_column('ncmr', sa.Column('_disposition_determined', sa.Integer(), nullable=True))
    op.add_column('ncmr', sa.Column('mrb_comments', sa.String(), nullable=True))
    op.add_column('ncmr', sa.Column('mrb_comments_raw', sa.String(), nullable=True))
    op.add_column('ncmr', sa.Column('_disposition_actual', sa.Integer(), nullable=True))
    op.add_column('ncmr', sa.Column('dsp_comments', sa.String(), nullable=True))
    op.add_column('ncmr', sa.Column('dsp_comments_raw', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ncmr', 'dsp_comments_raw')
    op.drop_column('ncmr', 'dsp_comments')
    op.drop_column('ncmr', '_disposition_actual')
    op.drop_column('ncmr', 'mrb_comments_raw')
    op.drop_column('ncmr', 'mrb_comments')
    op.drop_column('ncmr', '_disposition_determined')
    op.drop_column('ncmr', 'new_comments_raw')
    op.drop_column('ncmr', 'new_comments')
    # ### end Alembic commands ###
