"""empty message

Revision ID: 2680b22e54a4
Revises: c2c984067a84
Create Date: 2023-05-30 19:46:08.070844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2680b22e54a4'
down_revision = 'c2c984067a84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('_kind_id', sa.Integer(), nullable=True))
    op.drop_column('itemrevision', 'phase_0_due_utc')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itemrevision', sa.Column('phase_0_due_utc', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('item', '_kind_id')
    # ### end Alembic commands ###
