"""empty message

Revision ID: 26b61944de77
Revises: ab1a83916592
Create Date: 2023-05-31 20:39:38.678325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26b61944de77'
down_revision = 'ab1a83916592'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('custom_number', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('part_counter', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('sop_counter', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('wi_counter', sa.Integer(), nullable=True))
    op.drop_column('organizations', 'item_counter')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('item_counter', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('organizations', 'wi_counter')
    op.drop_column('organizations', 'sop_counter')
    op.drop_column('organizations', 'part_counter')
    op.drop_column('item', 'custom_number')
    # ### end Alembic commands ###
