"""empty message

Revision ID: 2b2c2c1ff4f7
Revises: f9d13ba0cda5
Create Date: 2023-06-10 17:51:55.503725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b2c2c1ff4f7'
down_revision = 'f9d13ba0cda5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chng', sa.Column('phase_99_due_utc', sa.BigInteger(), nullable=True))
    op.add_column('chng_approver_group', sa.Column('requires_all', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chng_approver_group', 'requires_all')
    op.drop_column('chng', 'phase_99_due_utc')
    # ### end Alembic commands ###
