"""empty message

Revision ID: 2c6d2cd5de6a
Revises: 5be4c6a78cb6
Create Date: 2023-05-07 10:30:58.063235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c6d2cd5de6a'
down_revision = '5be4c6a78cb6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lang', sa.String(length=2), nullable=True))
    op.drop_column('users', 'locale')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('locale', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.drop_column('users', 'lang')
    # ### end Alembic commands ###
