"""empty message

Revision ID: 301b43f5d9ee
Revises: 392861c636bb
Create Date: 2023-06-09 18:08:19.378186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '301b43f5d9ee'
down_revision = '392861c636bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chng', sa.Column('implementation_assignee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chng', 'users', ['implementation_assignee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chng', type_='foreignkey')
    op.drop_column('chng', 'implementation_assignee_id')
    # ### end Alembic commands ###
