"""empty message

Revision ID: 3152d1bb8225
Revises: 73ab0b8a024a
Create Date: 2023-06-14 16:55:34.528393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3152d1bb8225'
down_revision = '73ab0b8a024a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itemrevision', sa.Column('status_utc', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itemrevision', 'status_utc')
    # ### end Alembic commands ###
