"""empty message

Revision ID: 362ed7127eca
Revises: 7aec23f9ae7e
Create Date: 2023-06-04 23:07:23.543524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '362ed7127eca'
down_revision = '7aec23f9ae7e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chng', sa.Column('change_rationale', sa.String(), nullable=True, server_default=''))
    op.add_column('chng', sa.Column('change_rationale_raw', sa.String(), nullable=True, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chng', 'change_rationale_raw')
    op.drop_column('chng', 'change_rationale')
    # ### end Alembic commands ###
