"""empty message

Revision ID: 392861c636bb
Revises: 41f09426defa
Create Date: 2023-06-09 18:01:13.687436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392861c636bb'
down_revision = '41f09426defa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chng', sa.Column('phase_97_due_utc', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chng', 'phase_97_due_utc')
    # ### end Alembic commands ###
