"""empty message

Revision ID: 41f09426defa
Revises: e2290de7c1c5
Create Date: 2023-06-09 17:56:34.185121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41f09426defa'
down_revision = 'e2290de7c1c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chng_approver_relationship', sa.Column('record_id', sa.Integer(), nullable=True))
    op.drop_constraint('chng_user_approver_rel_unique', 'chng_approver_relationship', type_='unique')
    op.create_unique_constraint('chng_user_approver_rel_unique', 'chng_approver_relationship', ['record_id', 'user_id'])
    op.drop_constraint('chng_approver_relationship_change_id_fkey', 'chng_approver_relationship', type_='foreignkey')
    op.create_foreign_key(None, 'chng_approver_relationship', 'chng', ['record_id'], ['id'])
    op.drop_column('chng_approver_relationship', 'change_id')
    op.add_column('chng_assessor_relationship', sa.Column('record_id', sa.Integer(), nullable=True))
    op.drop_constraint('chng_user_assessor_rel_unique', 'chng_assessor_relationship', type_='unique')
    op.create_unique_constraint('chng_user_assessor_rel_unique', 'chng_assessor_relationship', ['record_id', 'user_id'])
    op.drop_constraint('chng_assessor_relationship_change_id_fkey', 'chng_assessor_relationship', type_='foreignkey')
    op.create_foreign_key(None, 'chng_assessor_relationship', 'chng', ['record_id'], ['id'])
    op.drop_column('chng_assessor_relationship', 'change_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chng_assessor_relationship', sa.Column('change_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chng_assessor_relationship', type_='foreignkey')
    op.create_foreign_key('chng_assessor_relationship_change_id_fkey', 'chng_assessor_relationship', 'chng', ['change_id'], ['id'])
    op.drop_constraint('chng_user_assessor_rel_unique', 'chng_assessor_relationship', type_='unique')
    op.create_unique_constraint('chng_user_assessor_rel_unique', 'chng_assessor_relationship', ['change_id', 'user_id'])
    op.drop_column('chng_assessor_relationship', 'record_id')
    op.add_column('chng_approver_relationship', sa.Column('change_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chng_approver_relationship', type_='foreignkey')
    op.create_foreign_key('chng_approver_relationship_change_id_fkey', 'chng_approver_relationship', 'chng', ['change_id'], ['id'])
    op.drop_constraint('chng_user_approver_rel_unique', 'chng_approver_relationship', type_='unique')
    op.create_unique_constraint('chng_user_approver_rel_unique', 'chng_approver_relationship', ['change_id', 'user_id'])
    op.drop_column('chng_approver_relationship', 'record_id')
    # ### end Alembic commands ###
