"""empty message

Revision ID: 4754c786b5d5
Revises: 67d8acc0ade0
Create Date: 2023-05-30 20:35:41.744446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4754c786b5d5'
down_revision = '67d8acc0ade0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('_status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', '_status')
    # ### end Alembic commands ###
