"""empty message

Revision ID: 520a2d5d4e93
Revises: d3b320da02e1
Create Date: 2023-05-19 22:43:35.022891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '520a2d5d4e93'
down_revision = 'd3b320da02e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capa', sa.Column('discoverer_id', sa.Integer(), nullable=True))
    op.add_column('capa', sa.Column('root_cause_investigator_id', sa.Integer(), nullable=True))
    op.add_column('capa', sa.Column('root_cause_analysis', sa.String(), nullable=True))
    op.add_column('capa', sa.Column('root_cause_analysis_raw', sa.String(), nullable=True))
    op.add_column('capa', sa.Column('scope_and_impact', sa.String(), nullable=True))
    op.add_column('capa', sa.Column('scope_and_impact_raw', sa.String(), nullable=True))
    op.add_column('capa', sa.Column('risk_assessment', sa.String(), nullable=True))
    op.add_column('capa', sa.Column('risk_assessment_raw', sa.String(), nullable=True))
    op.add_column('capa', sa.Column('action_plan', sa.String(), nullable=True))
    op.add_column('capa', sa.Column('action_plan_raw', sa.String(), nullable=True))
    op.add_column('capa', sa.Column('voe_plan', sa.String(), nullable=True))
    op.add_column('capa', sa.Column('voe_plan_raw', sa.String(), nullable=True))
    op.add_column('capa', sa.Column('action_assignee_id', sa.Integer(), nullable=True))
    op.add_column('capa', sa.Column('actions_taken', sa.String(), nullable=True))
    op.add_column('capa', sa.Column('actions_taken_raw', sa.String(), nullable=True))
    op.add_column('capa', sa.Column('voe_executed', sa.String(), nullable=True))
    op.add_column('capa', sa.Column('voe_executed_raw', sa.String(), nullable=True))
    op.drop_constraint('capa_who_discovered_fkey', 'capa', type_='foreignkey')
    op.create_foreign_key(None, 'capa', 'users', ['root_cause_investigator_id'], ['id'])
    op.create_foreign_key(None, 'capa', 'users', ['discoverer_id'], ['id'])
    op.create_foreign_key(None, 'capa', 'users', ['action_assignee_id'], ['id'])
    op.drop_column('capa', 'who_discovered')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capa', sa.Column('who_discovered', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'capa', type_='foreignkey')
    op.drop_constraint(None, 'capa', type_='foreignkey')
    op.drop_constraint(None, 'capa', type_='foreignkey')
    op.create_foreign_key('capa_who_discovered_fkey', 'capa', 'users', ['who_discovered'], ['id'])
    op.drop_column('capa', 'voe_executed_raw')
    op.drop_column('capa', 'voe_executed')
    op.drop_column('capa', 'actions_taken_raw')
    op.drop_column('capa', 'actions_taken')
    op.drop_column('capa', 'action_assignee_id')
    op.drop_column('capa', 'voe_plan_raw')
    op.drop_column('capa', 'voe_plan')
    op.drop_column('capa', 'action_plan_raw')
    op.drop_column('capa', 'action_plan')
    op.drop_column('capa', 'risk_assessment_raw')
    op.drop_column('capa', 'risk_assessment')
    op.drop_column('capa', 'scope_and_impact_raw')
    op.drop_column('capa', 'scope_and_impact')
    op.drop_column('capa', 'root_cause_analysis_raw')
    op.drop_column('capa', 'root_cause_analysis')
    op.drop_column('capa', 'root_cause_investigator_id')
    op.drop_column('capa', 'discoverer_id')
    # ### end Alembic commands ###
