"""empty message

Revision ID: 5383609205b1
Revises: c0666f2044ca
Create Date: 2023-05-16 21:55:32.503344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5383609205b1'
down_revision = 'c0666f2044ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_doc_control', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_mrb', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_mrb')
    op.drop_column('users', 'is_doc_control')
    # ### end Alembic commands ###
