"""empty message

Revision ID: 54d255e8e93a
Revises: 66bdf8018bae
Create Date: 2023-06-04 22:14:08.245543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d255e8e93a'
down_revision = '66bdf8018bae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chng', sa.Column('phase_0_due_utc', sa.BigInteger(), nullable=True))
    op.add_column('chng', sa.Column('record_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chng', 'record_name')
    op.drop_column('chng', 'phase_0_due_utc')
    # ### end Alembic commands ###
