"""empty message

Revision ID: 5be4c6a78cb6
Revises: 74cc241c71df
Create Date: 2023-05-07 10:27:23.206728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5be4c6a78cb6'
down_revision = '74cc241c71df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('locale', sa.String(length=2), nullable=True))
    op.drop_column('users', 'lang')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lang', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.drop_column('users', 'locale')
    # ### end Alembic commands ###
