"""empty message

Revision ID: 5c40b8d9b3de
Revises: 821e657db3d2
Create Date: 2023-05-29 17:28:20.023175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c40b8d9b3de'
down_revision = '821e657db3d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_utc', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itemrevision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_utc', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('_status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('organizations', sa.Column('part_counter', sa.Integer(), nullable=True))
    op.drop_column('organizations', 'tp_counter')
    op.drop_column('organizations', 'co_counter')
    op.drop_column('organizations', 'tr_counter')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('tr_counter', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('co_counter', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('tp_counter', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('organizations', 'part_counter')
    op.drop_table('itemrevision')
    op.drop_table('item')
    # ### end Alembic commands ###
