"""empty message

Revision ID: 6014e5812cc0
Revises: 5383609205b1
Create Date: 2023-05-16 22:12:49.867385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6014e5812cc0'
down_revision = '5383609205b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ncmr', sa.Column('assignee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ncmr', 'users', ['assignee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ncmr', type_='foreignkey')
    op.drop_column('ncmr', 'assignee_id')
    # ### end Alembic commands ###
