"""empty message

Revision ID: 629f221aa083
Revises: a91e36d337b9
Create Date: 2023-04-29 22:28:48.293616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '629f221aa083'
down_revision = 'a91e36d337b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('ncmr_counter', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('capa_counter', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('dev_counter', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('sop_counter', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('wi_counter', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('tp_counter', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('tr_counter', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('co_counter', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('is_banned', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('reset_pw_next_login', sa.Boolean(), nullable=True))
    op.create_unique_constraint('_email_org_unique', 'users', ['email', 'organization_id'])
    op.drop_column('users', 'referred_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referred_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('_email_org_unique', 'users', type_='unique')
    op.drop_column('users', 'reset_pw_next_login')
    op.drop_column('organizations', 'is_banned')
    op.drop_column('organizations', 'co_counter')
    op.drop_column('organizations', 'tr_counter')
    op.drop_column('organizations', 'tp_counter')
    op.drop_column('organizations', 'wi_counter')
    op.drop_column('organizations', 'sop_counter')
    op.drop_column('organizations', 'dev_counter')
    op.drop_column('organizations', 'capa_counter')
    op.drop_column('organizations', 'ncmr_counter')
    # ### end Alembic commands ###
