"""empty message

Revision ID: 64edbe4485c4
Revises: 801905796061
Create Date: 2023-06-04 21:11:25.541077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64edbe4485c4'
down_revision = '801905796061'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('rvsn_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'files', 'itemrevision', ['rvsn_id'], ['id'])
    op.create_unique_constraint('item_org_custom_number_unique', 'item', ['custom_number', 'organization_id'])
    op.drop_constraint('itemrevision_file_id_fkey', 'itemrevision', type_='foreignkey')
    op.drop_column('itemrevision', 'file_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itemrevision', sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('itemrevision_file_id_fkey', 'itemrevision', 'files', ['file_id'], ['id'])
    op.drop_constraint('item_org_custom_number_unique', 'item', type_='unique')
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_column('files', 'rvsn_id')
    # ### end Alembic commands ###
