"""empty message

Revision ID: 66bdf8018bae
Revises: 64edbe4485c4
Create Date: 2023-06-04 22:04:15.613701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66bdf8018bae'
down_revision = '64edbe4485c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chng',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('_status', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number', 'organization_id', name='chng_org_number_unique')
    )
    op.create_index(op.f('ix_chng_number'), 'chng', ['number'], unique=False)
    op.create_table('chng_approval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['chng.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chng_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.Integer(), nullable=True),
    sa.Column('created_ip', sa.String(length=64), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['chng.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('itemrevision', sa.Column('change_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'itemrevision', 'chng', ['change_id'], ['id'])
    op.add_column('organizations', sa.Column('chng_prefix', sa.String(length=5), nullable=True))
    op.add_column('organizations', sa.Column('chng_counter', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'chng_counter')
    op.drop_column('organizations', 'chng_prefix')
    op.drop_constraint(None, 'itemrevision', type_='foreignkey')
    op.drop_column('itemrevision', 'change_id')
    op.drop_table('chng_audit')
    op.drop_table('chng_approval')
    op.drop_index(op.f('ix_chng_number'), table_name='chng')
    op.drop_table('chng')
    # ### end Alembic commands ###
