"""empty message

Revision ID: 67d8acc0ade0
Revises: 33e170be6b79
Create Date: 2023-05-30 20:31:59.896755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67d8acc0ade0'
down_revision = '33e170be6b79'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'item', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_column('item', 'organization_id')
    # ### end Alembic commands ###
