"""empty message

Revision ID: 6cc9540b9ec0
Revises: 821a3feef8c8
Create Date: 2023-05-22 21:46:28.579448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cc9540b9ec0'
down_revision = '821a3feef8c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capa', sa.Column('phase_0_due_utc', sa.BigInteger(), nullable=True))
    op.add_column('capa', sa.Column('phase_1_due_utc', sa.BigInteger(), nullable=True))
    op.add_column('capa', sa.Column('phase_2_due_utc', sa.BigInteger(), nullable=True))
    op.add_column('capa', sa.Column('phase_3_due_utc', sa.BigInteger(), nullable=True))
    op.add_column('capa', sa.Column('phase_4_due_utc', sa.BigInteger(), nullable=True))
    op.add_column('capa', sa.Column('phase_5_due_utc', sa.BigInteger(), nullable=True))
    op.add_column('capa', sa.Column('phase_6_due_utc', sa.BigInteger(), nullable=True))
    op.add_column('ncmr', sa.Column('phase_0_due_utc', sa.BigInteger(), nullable=True))
    op.add_column('ncmr', sa.Column('phase_1_due_utc', sa.BigInteger(), nullable=True))
    op.add_column('ncmr', sa.Column('phase_2_due_utc', sa.BigInteger(), nullable=True))
    op.add_column('ncmr', sa.Column('phase_3_due_utc', sa.BigInteger(), nullable=True))
    op.add_column('ncmr', sa.Column('phase_4_due_utc', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ncmr', 'phase_4_due_utc')
    op.drop_column('ncmr', 'phase_3_due_utc')
    op.drop_column('ncmr', 'phase_2_due_utc')
    op.drop_column('ncmr', 'phase_1_due_utc')
    op.drop_column('ncmr', 'phase_0_due_utc')
    op.drop_column('capa', 'phase_6_due_utc')
    op.drop_column('capa', 'phase_5_due_utc')
    op.drop_column('capa', 'phase_4_due_utc')
    op.drop_column('capa', 'phase_3_due_utc')
    op.drop_column('capa', 'phase_2_due_utc')
    op.drop_column('capa', 'phase_1_due_utc')
    op.drop_column('capa', 'phase_0_due_utc')
    # ### end Alembic commands ###
