"""empty message

Revision ID: 738cdd98bd59
Revises: a0d2a4d33db2
Create Date: 2023-04-29 10:18:56.920347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '738cdd98bd59'
down_revision = 'a0d2a4d33db2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paypal_txns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.Integer(), nullable=True),
    sa.Column('paypal_id', sa.String(), nullable=True),
    sa.Column('usd_cents', sa.Integer(), nullable=True),
    sa.Column('seat_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('otp_secret', sa.String(length=64), nullable=True))
    op.drop_column('users', 'mfa_secret')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mfa_secret', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('users', 'otp_secret')
    op.drop_table('paypal_txns')
    # ### end Alembic commands ###
