"""empty message

Revision ID: 73ab0b8a024a
Revises: 974c476af109
Create Date: 2023-06-11 09:30:54.423485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73ab0b8a024a'
down_revision = '974c476af109'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capa_approval', sa.Column('user_name', sa.String(), nullable=True))
    op.add_column('chng_approval', sa.Column('user_name', sa.String(), nullable=True))
    op.add_column('dvtn_approval', sa.Column('user_name', sa.String(), nullable=True))
    op.add_column('ncmr_approval', sa.Column('user_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ncmr_approval', 'user_name')
    op.drop_column('dvtn_approval', 'user_name')
    op.drop_column('chng_approval', 'user_name')
    op.drop_column('capa_approval', 'user_name')
    # ### end Alembic commands ###
