"""empty message

Revision ID: 74cc241c71df
Revises: ad551e17ae26
Create Date: 2023-05-07 08:50:34.125630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74cc241c71df'
down_revision = 'ad551e17ae26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('default_lang', sa.String(length=2), nullable=True))
    op.add_column('users', sa.Column('lang', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lang')
    op.drop_column('organizations', 'default_lang')
    # ### end Alembic commands ###
