"""empty message

Revision ID: 7aec23f9ae7e
Revises: 54d255e8e93a
Create Date: 2023-06-04 23:05:02.275412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aec23f9ae7e'
down_revision = '54d255e8e93a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chng', sa.Column('change_description', sa.String(), nullable=True, server_default=""))
    op.add_column('chng', sa.Column('change_description_raw', sa.String(), nullable=True, server_default=""))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chng', 'change_description_raw')
    op.drop_column('chng', 'change_description')
    # ### end Alembic commands ###
