"""empty message

Revision ID: 7e6c972ff746
Revises: 6014e5812cc0
Create Date: 2023-05-17 19:30:19.568700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e6c972ff746'
down_revision = '6014e5812cc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('special_role', sa.Integer(), nullable=True))
    op.drop_column('users', 'is_doc_control')
    op.drop_column('users', 'is_mrb')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_mrb', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_doc_control', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'special_role')
    # ### end Alembic commands ###
