"""empty message

Revision ID: 7f7d43ddbb9a
Revises: 001318d7b056
Create Date: 2023-05-19 19:13:11.055030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f7d43ddbb9a'
down_revision = '001318d7b056'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_utc', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('_status', sa.Integer(), nullable=True),
    sa.Column('issue_source', sa.Integer(), nullable=True),
    sa.Column('describe_issue', sa.String(), nullable=True),
    sa.Column('describe_issue_raw', sa.String(), nullable=True),
    sa.Column('who_discovered', sa.Integer(), nullable=True),
    sa.Column('how_discovered', sa.String(), nullable=True),
    sa.Column('how_discovered_raw', sa.String(), nullable=True),
    sa.Column('nc_description', sa.String(), nullable=True),
    sa.Column('nc_description_raw', sa.String(), nullable=True),
    sa.Column('new_comments', sa.String(), nullable=True),
    sa.Column('new_comments_raw', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['who_discovered'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capa_number'), 'capa', ['number'], unique=False)
    op.create_table('capa_approval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['capa.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capa_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.Integer(), nullable=True),
    sa.Column('created_ip', sa.String(length=64), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['capa.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('ncmr_org_number_unique', 'ncmr', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ncmr_org_number_unique', 'ncmr', ['number', 'organization_id'])
    op.drop_table('capa_audit')
    op.drop_table('capa_approval')
    op.drop_index(op.f('ix_capa_number'), table_name='capa')
    op.drop_table('capa')
    # ### end Alembic commands ###
