"""empty message

Revision ID: 8010d9966688
Revises: 362ed7127eca
Create Date: 2023-06-07 20:30:37.114237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8010d9966688'
down_revision = '362ed7127eca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chng_approver_relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['change_id'], ['chng.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chng_assessor_relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['change_id'], ['chng.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('chng', sa.Column('phase_96_due_utc', sa.BigInteger(), nullable=True))
    op.create_unique_constraint('item_change_unique', 'itemrevision', ['item_id', 'change_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('item_change_unique', 'itemrevision', type_='unique')
    op.drop_column('chng', 'phase_96_due_utc')
    op.drop_table('chng_assessor_relationship')
    op.drop_table('chng_approver_relationship')
    # ### end Alembic commands ###
