"""empty message

Revision ID: 801905796061
Revises: 86586c5a5395
Create Date: 2023-06-04 10:00:10.343731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801905796061'
down_revision = '86586c5a5395'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itemrevision', sa.Column('revision_number', sa.Integer(), nullable=True))
    op.create_unique_constraint('item_rev_number_unique', 'itemrevision', ['item_id', 'revision_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('item_rev_number_unique', 'itemrevision', type_='unique')
    op.drop_column('itemrevision', 'revision_number')
    # ### end Alembic commands ###
