"""empty message

Revision ID: 821a3feef8c8
Revises: 16bc99828492
Create Date: 2023-05-22 17:37:05.919242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '821a3feef8c8'
down_revision = '16bc99828492'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('color', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'color')
    # ### end Alembic commands ###
