"""empty message

Revision ID: 821e657db3d2
Revises: ff9bd548ea50
Create Date: 2023-05-27 09:04:21.639276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '821e657db3d2'
down_revision = 'ff9bd548ea50'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('ncmr_prefix', sa.String(length=5), nullable=True))
    op.add_column('organizations', sa.Column('capa_prefix', sa.String(length=5), nullable=True))
    op.add_column('organizations', sa.Column('dvtn_prefix', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'dvtn_prefix')
    op.drop_column('organizations', 'capa_prefix')
    op.drop_column('organizations', 'ncmr_prefix')
    # ### end Alembic commands ###
