"""empty message

Revision ID: 8222ec0acf9f
Revises: e8b60e8f0e18
Create Date: 2023-05-13 19:05:09.158792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8222ec0acf9f'
down_revision = 'e8b60e8f0e18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ncmr_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ncmr_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.Integer(), nullable=True),
    sa.Column('created_ip', sa.String(length=64), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ncmr_id'], ['ncmr.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ncmr', sa.Column('created_utc', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ncmr', 'created_utc')
    op.drop_table('ncmr_audit')
    # ### end Alembic commands ###
