"""empty message

Revision ID: 86586c5a5395
Revises: 2199a70c0eec
Create Date: 2023-06-01 21:25:26.288803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86586c5a5395'
down_revision = '2199a70c0eec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('item_org_custom_number_unique', 'item', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('item_org_custom_number_unique', 'item', ['custom_number', 'organization_id'])
    # ### end Alembic commands ###
