"""empty message

Revision ID: 8f0ca8150c43
Revises: 90d03cd8b147
Create Date: 2023-06-10 19:14:41.557177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f0ca8150c43'
down_revision = '90d03cd8b147'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chng_approver_group', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chng_approver_group', 'is_active')
    # ### end Alembic commands ###
