"""empty message

Revision ID: 8f9334cd1425
Revises: 11331d4310b2
Create Date: 2023-06-19 00:09:50.013646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f9334cd1425'
down_revision = '11331d4310b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capa_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['capa.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id', 'user_id', name='capa_view_user_unique')
    )
    op.create_index(op.f('ix_capa_view_record_id'), 'capa_view', ['record_id'], unique=False)
    op.create_index(op.f('ix_capa_view_user_id'), 'capa_view', ['user_id'], unique=False)
    op.create_table('chng_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['chng.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id', 'user_id', name='change_view_user_unique')
    )
    op.create_index(op.f('ix_chng_view_record_id'), 'chng_view', ['record_id'], unique=False)
    op.create_index(op.f('ix_chng_view_user_id'), 'chng_view', ['user_id'], unique=False)
    op.create_table('dvtn_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['dvtn.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id', 'user_id', name='dvtn_view_user_unique')
    )
    op.create_index(op.f('ix_dvtn_view_record_id'), 'dvtn_view', ['record_id'], unique=False)
    op.create_index(op.f('ix_dvtn_view_user_id'), 'dvtn_view', ['user_id'], unique=False)
    op.create_table('ncmr_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['ncmr.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id', 'user_id', name='ncmr_view_user_unique')
    )
    op.create_index(op.f('ix_ncmr_view_record_id'), 'ncmr_view', ['record_id'], unique=False)
    op.create_index(op.f('ix_ncmr_view_user_id'), 'ncmr_view', ['user_id'], unique=False)
    op.add_column('item_view', sa.Column('record_id', sa.Integer(), nullable=True))
    op.drop_index('ix_item_view_item_id', table_name='item_view')
    op.drop_constraint('item_view_user_unique', 'item_view', type_='unique')
    op.create_unique_constraint('item_view_user_unique', 'item_view', ['record_id', 'user_id'])
    op.create_index(op.f('ix_item_view_record_id'), 'item_view', ['record_id'], unique=False)
    op.drop_constraint('item_view_item_id_fkey', 'item_view', type_='foreignkey')
    op.create_foreign_key(None, 'item_view', 'item', ['record_id'], ['id'])
    op.drop_column('item_view', 'item_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_view', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'item_view', type_='foreignkey')
    op.create_foreign_key('item_view_item_id_fkey', 'item_view', 'item', ['item_id'], ['id'])
    op.drop_index(op.f('ix_item_view_record_id'), table_name='item_view')
    op.drop_constraint('item_view_user_unique', 'item_view', type_='unique')
    op.create_unique_constraint('item_view_user_unique', 'item_view', ['item_id', 'user_id'])
    op.create_index('ix_item_view_item_id', 'item_view', ['item_id'], unique=False)
    op.drop_column('item_view', 'record_id')
    op.drop_index(op.f('ix_ncmr_view_user_id'), table_name='ncmr_view')
    op.drop_index(op.f('ix_ncmr_view_record_id'), table_name='ncmr_view')
    op.drop_table('ncmr_view')
    op.drop_index(op.f('ix_dvtn_view_user_id'), table_name='dvtn_view')
    op.drop_index(op.f('ix_dvtn_view_record_id'), table_name='dvtn_view')
    op.drop_table('dvtn_view')
    op.drop_index(op.f('ix_chng_view_user_id'), table_name='chng_view')
    op.drop_index(op.f('ix_chng_view_record_id'), table_name='chng_view')
    op.drop_table('chng_view')
    op.drop_index(op.f('ix_capa_view_user_id'), table_name='capa_view')
    op.drop_index(op.f('ix_capa_view_record_id'), table_name='capa_view')
    op.drop_table('capa_view')
    # ### end Alembic commands ###
