"""empty message

Revision ID: 90d03cd8b147
Revises: 2b2c2c1ff4f7
Create Date: 2023-06-10 17:52:18.695377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90d03cd8b147'
down_revision = '2b2c2c1ff4f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chng_approver_group', 'requires_all',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chng_approver_group', 'requires_all',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
