"""empty message

Revision ID: 974c476af109
Revises: 8f0ca8150c43
Create Date: 2023-06-10 19:18:53.923820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '974c476af109'
down_revision = '8f0ca8150c43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chng_approver_group', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chng_approver_group', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
