"""empty message

Revision ID: 9aa70866fc8a
Revises: 5c40b8d9b3de
Create Date: 2023-05-29 21:06:39.793068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aa70866fc8a'
down_revision = '5c40b8d9b3de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itemrelationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itemrelationship')
    # ### end Alembic commands ###
