"""empty message

Revision ID: a0d2a4d33db2
Revises: 
Create Date: 2023-04-27 19:53:10.952438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0d2a4d33db2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('license_count', sa.Integer(), nullable=True),
    sa.Column('license_expire_utc', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.Integer(), nullable=True),
    sa.Column('creation_ip', sa.String(), nullable=True),
    sa.Column('is_mfa_required', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('passhash', sa.String(), nullable=True),
    sa.Column('created_utc', sa.Integer(), nullable=True),
    sa.Column('creation_ip', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('referred_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('has_license', sa.Boolean(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('login_nonce', sa.Integer(), nullable=True),
    sa.Column('mfa_secret', sa.String(length=64), nullable=True),
    sa.Column('has_profile', sa.Boolean(), nullable=True),
    sa.Column('profile_nonce', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('users_email_trgm_idx', 'users', ['email'], unique=False, postgresql_using='gin', postgresql_ops={'email': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('users_email_trgm_idx', table_name='users', postgresql_using='gin', postgresql_ops={'email': 'gin_trgm_ops'})
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
