"""empty message

Revision ID: a3fbe3a15cc4
Revises: 18094fc90c08
Create Date: 2023-04-30 17:17:43.876035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3fbe3a15cc4'
down_revision = '18094fc90c08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paypal_txns', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'paypal_txns', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'paypal_txns', type_='foreignkey')
    op.drop_column('paypal_txns', 'organization_id')
    # ### end Alembic commands ###
