"""empty message

Revision ID: a4a21c06adef
Revises: 301b43f5d9ee
Create Date: 2023-06-09 18:18:19.463424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4a21c06adef'
down_revision = '301b43f5d9ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chng', sa.Column('phase_95_due_utc', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chng', 'phase_95_due_utc')
    # ### end Alembic commands ###
