"""empty message

Revision ID: a710212c372b
Revises: 3152d1bb8225
Create Date: 2023-06-18 23:48:19.326781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a710212c372b'
down_revision = '3152d1bb8225'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_view_item_id'), 'item_view', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_view_user_id'), 'item_view', ['user_id'], unique=False)
    op.create_index(op.f('ix_capa_organization_id'), 'capa', ['organization_id'], unique=False)
    op.create_index(op.f('ix_capa_approval_record_id'), 'capa_approval', ['record_id'], unique=False)
    op.create_index(op.f('ix_capa_audit_record_id'), 'capa_audit', ['record_id'], unique=False)
    op.create_index(op.f('ix_chng_organization_id'), 'chng', ['organization_id'], unique=False)
    op.create_index(op.f('ix_chng_approval_record_id'), 'chng_approval', ['record_id'], unique=False)
    op.create_index(op.f('ix_chng_approver_group_organization_id'), 'chng_approver_group', ['organization_id'], unique=False)
    op.create_index(op.f('ix_chng_approver_relationship_group_id'), 'chng_approver_relationship', ['group_id'], unique=False)
    op.create_index(op.f('ix_chng_approver_relationship_record_id'), 'chng_approver_relationship', ['record_id'], unique=False)
    op.create_index(op.f('ix_chng_audit_record_id'), 'chng_audit', ['record_id'], unique=False)
    op.create_index(op.f('ix_chnge_approver_group_relationship_record_id'), 'chnge_approver_group_relationship', ['record_id'], unique=False)
    op.create_index(op.f('ix_chnge_approver_group_relationship_user_id'), 'chnge_approver_group_relationship', ['user_id'], unique=False)
    op.create_index(op.f('ix_dvtn_organization_id'), 'dvtn', ['organization_id'], unique=False)
    op.create_index(op.f('ix_dvtn_approval_record_id'), 'dvtn_approval', ['record_id'], unique=False)
    op.create_index(op.f('ix_dvtn_audit_record_id'), 'dvtn_audit', ['record_id'], unique=False)
    op.create_index(op.f('ix_files_capa_id'), 'files', ['capa_id'], unique=False)
    op.create_index(op.f('ix_files_chng_id'), 'files', ['chng_id'], unique=False)
    op.create_index(op.f('ix_files_dvtn_id'), 'files', ['dvtn_id'], unique=False)
    op.create_index(op.f('ix_files_ncmr_id'), 'files', ['ncmr_id'], unique=False)
    op.create_index(op.f('ix_files_organization_id'), 'files', ['organization_id'], unique=False)
    op.create_index(op.f('ix_files_rvsn_id'), 'files', ['rvsn_id'], unique=False)
    op.create_index(op.f('ix_item_audit_record_id'), 'item_audit', ['record_id'], unique=False)
    op.create_index(op.f('ix_itemrelationship_child_id'), 'itemrelationship', ['child_id'], unique=False)
    op.create_index(op.f('ix_itemrelationship_parent_id'), 'itemrelationship', ['parent_id'], unique=False)
    op.create_index(op.f('ix_itemrevision_item_id'), 'itemrevision', ['item_id'], unique=False)
    op.create_index(op.f('ix_ncmr_organization_id'), 'ncmr', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ncmr_approval_record_id'), 'ncmr_approval', ['record_id'], unique=False)
    op.create_index(op.f('ix_ncmr_audit_record_id'), 'ncmr_audit', ['record_id'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_ncmr_audit_record_id'), table_name='ncmr_audit')
    op.drop_index(op.f('ix_ncmr_approval_record_id'), table_name='ncmr_approval')
    op.drop_index(op.f('ix_ncmr_organization_id'), table_name='ncmr')
    op.drop_index(op.f('ix_itemrevision_item_id'), table_name='itemrevision')
    op.drop_index(op.f('ix_itemrelationship_parent_id'), table_name='itemrelationship')
    op.drop_index(op.f('ix_itemrelationship_child_id'), table_name='itemrelationship')
    op.drop_index(op.f('ix_item_audit_record_id'), table_name='item_audit')
    op.drop_index(op.f('ix_files_rvsn_id'), table_name='files')
    op.drop_index(op.f('ix_files_organization_id'), table_name='files')
    op.drop_index(op.f('ix_files_ncmr_id'), table_name='files')
    op.drop_index(op.f('ix_files_dvtn_id'), table_name='files')
    op.drop_index(op.f('ix_files_chng_id'), table_name='files')
    op.drop_index(op.f('ix_files_capa_id'), table_name='files')
    op.drop_index(op.f('ix_dvtn_audit_record_id'), table_name='dvtn_audit')
    op.drop_index(op.f('ix_dvtn_approval_record_id'), table_name='dvtn_approval')
    op.drop_index(op.f('ix_dvtn_organization_id'), table_name='dvtn')
    op.drop_index(op.f('ix_chnge_approver_group_relationship_user_id'), table_name='chnge_approver_group_relationship')
    op.drop_index(op.f('ix_chnge_approver_group_relationship_record_id'), table_name='chnge_approver_group_relationship')
    op.drop_index(op.f('ix_chng_audit_record_id'), table_name='chng_audit')
    op.drop_index(op.f('ix_chng_approver_relationship_record_id'), table_name='chng_approver_relationship')
    op.drop_index(op.f('ix_chng_approver_relationship_group_id'), table_name='chng_approver_relationship')
    op.drop_index(op.f('ix_chng_approver_group_organization_id'), table_name='chng_approver_group')
    op.drop_index(op.f('ix_chng_approval_record_id'), table_name='chng_approval')
    op.drop_index(op.f('ix_chng_organization_id'), table_name='chng')
    op.drop_index(op.f('ix_capa_audit_record_id'), table_name='capa_audit')
    op.drop_index(op.f('ix_capa_approval_record_id'), table_name='capa_approval')
    op.drop_index(op.f('ix_capa_organization_id'), table_name='capa')
    op.drop_index(op.f('ix_item_view_user_id'), table_name='item_view')
    op.drop_index(op.f('ix_item_view_item_id'), table_name='item_view')
    op.drop_table('item_view')
    # ### end Alembic commands ###
