"""empty message

Revision ID: ad551e17ae26
Revises: da272dbc7cad
Create Date: 2023-05-06 11:18:59.104566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad551e17ae26'
down_revision = 'da272dbc7cad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_upload_ip', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_upload_region', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_upload_region')
    op.drop_column('users', 'profile_upload_ip')
    # ### end Alembic commands ###
