"""empty message

Revision ID: b793e2d1dec6
Revises: 26b61944de77
Create Date: 2023-06-01 21:22:36.538729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b793e2d1dec6'
down_revision = '26b61944de77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('part_prefix', sa.String(length=5), nullable=True))
    op.add_column('organizations', sa.Column('sop_prefix', sa.String(length=5), nullable=True))
    op.add_column('organizations', sa.Column('wi_prefix', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'wi_prefix')
    op.drop_column('organizations', 'sop_prefix')
    op.drop_column('organizations', 'part_prefix')
    # ### end Alembic commands ###
