"""empty message

Revision ID: caff1e1e53c0
Revises: 2c6d2cd5de6a
Create Date: 2023-05-07 17:41:42.439976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caff1e1e53c0'
down_revision = '2c6d2cd5de6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('default_tz', sa.String(), nullable=True))
    op.add_column('users', sa.Column('tz', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tz')
    op.drop_column('organizations', 'default_tz')
    # ### end Alembic commands ###
