"""empty message

Revision ID: d3b320da02e1
Revises: 7f7d43ddbb9a
Create Date: 2023-05-19 19:19:47.406080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3b320da02e1'
down_revision = '7f7d43ddbb9a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('capa_org_number_unique', 'capa', ['number', 'organization_id'])
    op.create_unique_constraint('ncmr_org_number_unique', 'ncmr', ['number', 'organization_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ncmr_org_number_unique', 'ncmr', type_='unique')
    op.drop_constraint('capa_org_number_unique', 'capa', type_='unique')
    # ### end Alembic commands ###
