"""empty message

Revision ID: da272dbc7cad
Revises: 13fd57d7ea65
Create Date: 2023-05-06 11:18:14.569688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da272dbc7cad'
down_revision = '13fd57d7ea65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'title')
    # ### end Alembic commands ###
