"""empty message

Revision ID: ddd8940515bc
Revises: 8f9334cd1425
Create Date: 2023-06-26 19:26:51.396934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddd8940515bc'
down_revision = '8f9334cd1425'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itemrevision', sa.Column('revision_item_lifecycle_to', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itemrevision', 'revision_item_lifecycle_to')
    # ### end Alembic commands ###
