"""empty message

Revision ID: e08b5fdd2d44
Revises: caff1e1e53c0
Create Date: 2023-05-07 18:36:17.312568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e08b5fdd2d44'
down_revision = 'caff1e1e53c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('lang', sa.String(length=2), nullable=True))
    op.add_column('organizations', sa.Column('tz', sa.String(), nullable=True))
    op.drop_column('organizations', 'default_tz')
    op.drop_column('organizations', 'default_lang')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('default_lang', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('default_tz', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('organizations', 'tz')
    op.drop_column('organizations', 'lang')
    # ### end Alembic commands ###
