"""empty message

Revision ID: e1fb906f0441
Revises: 738cdd98bd59
Create Date: 2023-04-29 10:35:32.040235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1fb906f0441'
down_revision = '738cdd98bd59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('requires_otp', sa.Boolean(), nullable=True))
    op.drop_column('organizations', 'is_mfa_required')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('is_mfa_required', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('organizations', 'requires_otp')
    # ### end Alembic commands ###
