"""empty message

Revision ID: e2290de7c1c5
Revises: 8010d9966688
Create Date: 2023-06-08 22:39:23.817474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2290de7c1c5'
down_revision = '8010d9966688'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('chng_user_approver_rel_unique', 'chng_approver_relationship', ['change_id', 'user_id'])
    op.create_unique_constraint('chng_user_assessor_rel_unique', 'chng_assessor_relationship', ['change_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chng_user_assessor_rel_unique', 'chng_assessor_relationship', type_='unique')
    op.drop_constraint('chng_user_approver_rel_unique', 'chng_approver_relationship', type_='unique')
    # ### end Alembic commands ###
