"""empty message

Revision ID: e8b60e8f0e18
Revises: bbdcd5bdde6a
Create Date: 2023-05-13 18:53:55.354471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8b60e8f0e18'
down_revision = 'bbdcd5bdde6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ncmr_number'), 'ncmr', ['number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ncmr_number'), table_name='ncmr')
    # ### end Alembic commands ###
