"""empty message

Revision ID: f08924ffcd80
Revises: 1298331da4eb
Create Date: 2023-04-30 15:43:47.439682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f08924ffcd80'
down_revision = '1298331da4eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_log', 'old_value')
    op.drop_column('organization_log', 'note')
    op.add_column('organizations', sa.Column('licenses_last_increased_utc', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'licenses_last_increased_utc')
    op.add_column('organization_log', sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organization_log', sa.Column('old_value', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
