"""empty message

Revision ID: f226907fbfac
Revises: 52a2a518f672
Create Date: 2023-04-30 09:12:04.494059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f226907fbfac'
down_revision = '52a2a518f672'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_log', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'organization_log', 'organizations', ['organization_id'], ['id'])
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'has_license',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_org_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'reset_pw_next_login',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'has_profile',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'has_profile',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'reset_pw_next_login',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_org_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'has_license',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(None, 'organization_log', type_='foreignkey')
    op.drop_column('organization_log', 'organization_id')
    # ### end Alembic commands ###
