"""empty message

Revision ID: f770130d3180
Revises: 1b5228be1198
Create Date: 2023-05-24 17:42:26.241586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f770130d3180'
down_revision = '1b5228be1198'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.drop_constraint('files_created_by_fkey', 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'users', ['creator_id'], ['id'])
    op.drop_column('files', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.create_foreign_key('files_created_by_fkey', 'files', 'users', ['created_by'], ['id'])
    op.drop_column('files', 'creator_id')
    # ### end Alembic commands ###
