"""empty message

Revision ID: f9d13ba0cda5
Revises: 258519d1fe46
Create Date: 2023-06-10 17:28:16.990797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9d13ba0cda5'
down_revision = '258519d1fe46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('chng_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'files', 'chng', ['chng_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_column('files', 'chng_id')
    # ### end Alembic commands ###
