"""empty message

Revision ID: ff9bd548ea50
Revises: 0e2ab5ebd716
Create Date: 2023-05-26 18:32:36.767223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff9bd548ea50'
down_revision = '0e2ab5ebd716'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('status_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'status_id')
    # ### end Alembic commands ###
